[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "AstroSuite"
version = "1.00r"
description = "Astronomy research-focused software collection written in Python"
readme = "README.md"
requires-python = ">=3.9"
license = {text = "MIT"}
authors = [
	{name='Dylan \"squimble"\ W.'} 
]
classifiers =[
	"Programming Language :: Python :: 3",
	"License :: OSI Approved :: MIT License",
	#sorry for not making it work with Windows :(
	"Operating System :: POSIX :: Linux"
]
dependencies = [
	"astropy>=8.0",
	#this may be redundant, but i could honestly not care
	#better to be safe than sorry
	"astroquery>=0.4",
	"pandas>=2.00"
]

[project.scripts]
astrosuite = "astrosuite.main:main"

[tool.hatch.build.targets.wheel]
packages = ["astrosuite"]

